name: " ↗️  Create Version Bump PR For Ruby Gems & NPM Packages"

on:
  workflow_dispatch:
    inputs:
      versionBump:
        description: 'Version Bump'
        required: true
        default: 'patch'
        type: choice
        options:
        - patch
        - minor
        - major

permissions:
  contents: write
  pull-requests: write

jobs:
  bump:
    runs-on: ubuntu-latest

    steps:
    - uses: "actions/checkout@v3"

    - uses: "ruby/setup-ruby@v1"
      with:
        bundler-cache: true

    - name: Enable corepack
      run: corepack enable

    - uses: "actions/setup-node@v4"
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'

    - name: "Install bump"
      run: gem install bump

    - name: "Install thor"
      run: gem install thor

    - name: "Bump all"
      id: bump-all
      run: ./bin/bump-all ${{ inputs.versionBump }}

    - name: "Create Pull Request"
      id: cpr
      uses: peter-evans/create-pull-request@v5
      with:
        author: "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
        committer: "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
        commit-message: "Version bump: ${{ inputs.versionBump }} - ${{ steps.bump-all.outputs.NEW_VERSION_NUMBER }}"
        branch: "version-bump/${{ steps.bump-all.outputs.NEW_VERSION_NUMBER }}"
        delete-branch: true
        title: "Version bump: ${{ inputs.versionBump }} - ${{ steps.bump-all.outputs.NEW_VERSION_NUMBER }}"
        add-paths: "bullet_train*,lib*,CHANGELOG.md"
        token: ${{ secrets.UPGRADE_PR_PAT }}
        body: |
          Version bump of the `core` ruby gems and npm packages with a step of\: `${{ inputs.versionBump }}`

          New version number: ${{ steps.bump-all.outputs.NEW_VERSION_NUMBER }}

          Tag v${{ steps.bump-all.outputs.NEW_VERSION_NUMBER }}

          Note: Merging this PR will trigger the following actions:
            * The `main` branch will be tagged with `v${{ steps.bump-all.outputs.NEW_VERSION_NUMBER }}`
            * A GitHub Release will be created for `v${{ steps.bump-all.outputs.NEW_VERSION_NUMBER }}`
            * Version `${{ steps.bump-all.outputs.NEW_VERSION_NUMBER }}` of the gems will be pushed to rubygems.org
            * Version `${{ steps.bump-all.outputs.NEW_VERSION_NUMBER }}` of the npm packages will be pushed to npmjs.com

          - Auto-generated by [create-pull-request][1] via `.github/workflows/version-bump.yml`

          [1]: https://github.com/peter-evans/create-pull-request
        labels: |
          version bump
        #reviewers: andreculver,jagthedrummer,pascallaliberte
